# Site settings
title:              Minghe Jiang Project Portfolio
email:              minghej@u.northwestern.edu
description:        "Portfolio template for Minghe Jiang"
url:                "http://localhost:4000"
baseurl:            /portfolio

# File structure settings
image_path:         /public/images

# Build settings
markdown:           kramdown
permalink:          pretty

# Collection definitions and settings
collections:
  projects:
    output: true
    permalink: /projects/:path/
